---
# ansible playbook that adds ssh fingerprints to known_hosts
- hosts: all
  connection: local
  serial: 1
  gather_facts: no
  tasks:
  - command: /usr/bin/ssh-keyscan -T 10 {{ ansible_host }}
    register: keyscan
  - debug:
          msg: "{{ keyscan.stdout }}"
  - lineinfile:
      path: ~/.ssh/known_hosts
      create: yes
      line: "{{ item }}"
    with_items: "{{ keyscan.stdout_lines[0] }}"
